spring:
  datasource:
    # 메모리 내에 H2 데이터베이스를 생성, H2 데이터베이스를 메모리 모드로 사용하도록 설정 (테스트 및 개발 환경에서 주로 사용)
    url: jdbc:h2:mem:testdb

  h2:
    console:
      # H2 콘솔을 활성화하여 브라우저에서 데이터베이스 상태를 확인할 수 있도록 함
      enabled: true

  jpa:
    # JPA가 실행하는 SQL 쿼리를 로그에 출력하여 개발 시 쿼리 확인을 용이하게 함
    show-sql: true
    properties:
      hibernate:
        # 출력되는 SQL 쿼리를 가독성 있게 포맷팅하여 보여줌
        format_sql: true

    # 애플리케이션 실행 시 데이터베이스 초기화(data.sql 실행)를 지연시켜,
    # 필요한 시점에 초기화 작업이 이루어지도록 설정
    defer-datasource-initialization: true
